'use client';

import { motion } from 'framer-motion';
import { ShieldCheck, EyeOff, Lock, Server, FileText, CheckCircle } from 'lucide-react';

export default function PrivacyPage() {
  const policies = [
    {
      title: "Memory-Only Processing",
      desc: "Our servers act as a bypass. Files are processed in volatile memory and streamed directly to S3. They never touch a persistent hard drive on our application server.",
      icon: <EyeOff className="w-5 h-5 text-primary" />
    },
    {
      title: "Data Encryption",
      desc: "All transfers are protected by SSL/TLS encryption. Files stored in S3 are encrypted at rest using industry-standard AES-256 algorithms.",
      icon: <Lock className="w-5 h-5 text-accent" />
    },
    {
      title: "Automated Expiration",
      desc: "Accessibility links generated by our platform expire after 10 minutes. This prevents accidental exposure and ensures your data remains private over time.",
      icon: <ShieldCheck className="w-5 h-5 text-primary" />
    },
    {
      title: "Zero Third-Party Tracking",
      desc: "We do not use tracking cookies or sell your metadata to third parties. Your upload history is not stored in any local database.",
      icon: <Server className="w-5 h-5 text-accent" />
    }
  ];

  return (
    <div className="max-w-4xl mx-auto px-4">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-16"
      >
        <div className="flex items-center gap-3 mb-6">
          <div className="p-2 bg-accent/10 rounded-lg">
            <ShieldCheck className="w-6 h-6 text-accent" />
          </div>
          <h1 className="text-4xl font-extrabold tracking-tight">Privacy <span className="text-accent">First</span> Policy</h1>
        </div>
        <p className="text-foreground/60 text-lg leading-relaxed max-w-3xl font-medium">
          At S3 Transmit, your privacy is not an afterthought—it's the core of our architecture. 
          We believe in total transparency regarding how your data is handled.
        </p>
      </motion.div>

      <div className="space-y-6 mb-20">
        {policies.map((policy, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: i * 0.1 }}
            className="p-6 rounded-2xl glass-morphism border border-white/5 flex gap-6 items-start"
          >
            <div className="p-3 bg-white/5 rounded-xl shrink-0">
              {policy.icon}
            </div>
            <div>
              <h3 className="text-lg font-bold mb-2">{policy.title}</h3>
              <p className="text-foreground/50 leading-relaxed text-sm font-medium">
                {policy.desc}
              </p>
            </div>
          </motion.div>
        ))}
      </div>

      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.5 }}
        className="glass border border-white/5 rounded-3xl p-10"
      >
        <div className="flex items-center gap-2 mb-6 text-foreground/40 font-bold uppercase text-[10px] tracking-widest">
          <FileText className="w-4 h-4" />
          General Terms
        </div>
        <div className="space-y-4">
          {[
            "We do not inspect or monitor the content of your files.",
            "Admin access is restricted to infrastructure management only.",
            "Public access to the storage bucket is strictly disabled.",
            "All session data is cleared upon browser closure."
          ].map((item, i) => (
            <div key={i} className="flex items-center gap-3">
              <CheckCircle className="w-4 h-4 text-primary shrink-0" />
              <span className="text-foreground/70 font-medium text-sm">{item}</span>
            </div>
          ))}
        </div>
      </motion.div>
    </div>
  );
}
